# admin-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        image: your-registry/admin-service:latest  # Update with your image
        ports:
        - containerPort: 5002
        env:
        - name: MONGO_URI
          value: "mongodb://admin:adminpassword@mongodb:27017/admin_db?authSource=admin"
        envFrom:
        - secretRef:
            name: admin-service-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002

---
apiVersion: v1
kind: Secret
metadata:
  name: admin-service-secrets
type: Opaque
stringData:
  .env.docker: |
    # Contents of your ./backend/admin-service/.env.docker file
    # (Remove this comment and paste the actual content)