# driver-frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-frontend
  template:
    metadata:
      labels:
        app: driver-frontend
    spec:
      containers:
      - name: driver-frontend
        image: your-registry/driver-frontend:latest  # Update with your image
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: driver-frontend
spec:
  type: LoadBalancer  # Or NodePort if you're not using a cloud provider
  selector:
    app: driver-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # Only for NodePort type, optional