version: '3'
services:
  ride-service:
    build: .
    ports:
      - "3001:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb://mongo:27017/ride-service
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" 